### ISSUE TITLE
Tracking issue: High-level modules for KDE applications

### ISSUE THREAD

**Issue by SigmaSquadron** [nix-community/plasma-manager#398]
We're currently missing a lot of apps. Let's organise the imporant ones in a single tracking issue.

---

### Development

- [x] [**Kate**](https://apps.kde.org/kate/) https://github.com/nix-community/plasma-manager/pull/88

### Graphics

- [x] [**Okular**](https://apps.kde.org/okular/) https://github.com/nix-community/plasma-manager/pull/244

### Internet

- [ ] [KDE PIM](https://kontact.kde.org/) https://github.com/nix-community/plasma-manager/issues/111
- [ ] [KDE Connect](https://apps.kde.org/kdeconnect/) **Options:** Per-device databases for custom commands, as well as the hostname.
- [ ] [NeoChat](https://apps.kde.org/neochat/) **Note:** Matrix clients are notoriously difficult to configure, as they're extremely stateful. 

### Multimedia

- [x] [**Elisa**](https://apps.kde.org/elisa/) https://github.com/nix-community/plasma-manager/pull/391

### Office

- [ ] [Calligra](https://calligra.org/) - **Note:** I'm the Calligra maintainer on Nixpkgs; I may be able to help with this.
- [x] [**Ghostwriter**](https://apps.kde.org/ghostwriter/) https://github.com/nix-community/plasma-manager/pull/342
- [ ] [Marknote](https://apps.kde.org/marknote/)
- [ ] [Merkuro](https://apps.kde.org/merkuro/) **Note:** This requires the KDE PIM module.

### System

- [ ] [Dolphin](https://apps.kde.org/dolphin/) **Note:** Dolphin is obviously a large application.
- [x] [**Konsole**](https://apps.kde.org/konsole/) https://github.com/nix-community/plasma-manager/pull/69
- [ ] [KWalletManager](https://apps.kde.org/kwalletmanager5/) **Note:** KWallet is pretty nonsensical at times so making a working module for this may be difficult.
- [ ] [Plasma System Monitor](https://apps.kde.org/plasma-systemmonitor/) **Options:** Many free-form options for configuring each system monitor panel.

### Utilities

- [ ] [Ark](https://apps.kde.org/ark/) **Note:** Quite a large application.
- [ ] [Kleopatra](https://apps.kde.org/kleopatra/) **Options:** Various local and external OpenPGP/Cert options.
- [x] [**Spectacle**](https://apps.kde.org/spectacle/) https://github.com/nix-community/plasma-manager/pull/27

**Comment by HeitorAugustoLN** [comment]
I think this list is too extensive, we should only support some applications, that come default with plasma, and some other popular applications

**Comment by HeitorAugustoLN** [comment]
Also, many of these applications are so simple that they don't even have configuration. So they don't need a module, such as kcolorchooser.

**Comment by bew** [comment]
Yes, keep in mind that this is plasma-manager, not kde-manager

**Comment by SigmaSquadron** [comment]
Yes, I started with an exhaustive list that can be reduced afterwards. Check the updated list, and see if I've deleted anything essential, or if more should be deleted.

**Comment by SigmaSquadron** [comment]
There are quite a few duplicates as well. Ghostwriter, Marknote and KleverNotes all do the same thing, but Marknote seems the newest of the three.

**Comment by SigmaSquadron** [comment]
We're down to 48 apps. There are a few more I think could be removed, but we'd be removing unique and/or popular apps.

**Comment by bew** [comment]
⚠️ Also I think we need to be careful about the maintanability of this repo, because as we add support for more apps, support issues can rise as programs are updated, adding/removing options, or changing how the config is done (without necessarily telling you about it since usually these programs expect to be configured manually..)..

I'm not saying this is the way to go, but maybe we could split some(all?) non-builtin-to-Plasma apps to a separate repo 🤔

**Comment by SigmaSquadron** [comment]
Well, the same could be said for Nixpkgs, and yet people write modules anyway. This issue is supposed to be completed in the long term; I'm not proposing that the current contributor team be responsible for every single KDE application.

**Comment by bew** [comment]
> Well, the same could be said for Nixpkgs, and yet people write modules anyway.

True, and modules should actually now use settings-options instead of having a explicit options for everything (mentioning difficulty to write, review, maintain, work with such full modules).
See https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md

I personally always consider how likely to change are the configs of a tool before using their modules, and sometimes just don't for things that are not really supposted to be declaratively configured / with 'volatile' config files..

**Comment by Asqiir** [comment]
I might chime in:
How about making 2 different repos, where one is `plasma-manager` (meant to manager the plasma desktop) and the other one is `konfigurator` (meant to manage config files that don't work well as symlinks, such as (famously) the config files by kde programs).

**Comment by magnouvean** [comment]
I do agree in general think that if we were to actually support this many apps that we would have maintainability difficulties, but we'd probably just have to rely on PRs. Having this in a separate repo could make sense, but I also think some of this could be in home-manager as well (at least kdenlive and krita and whatnot). I'm not sure the stance they take on non-symlink config-files though.

Splitting it into another repo would also not immediately help maintainability as I see it. There's also the fact that kde plasma also needs to manage files that don't work well as symlinks. I think having options for some core applications makes sense, but perhaps not all of them. The ones in bold above I think at the very least makes sense to have in this project.

**Comment by SigmaSquadron** [comment]
List has been trimmed again. The bare essentials should be actionable.

**Comment by HeitorAugustoLN** [comment]
This list looks really good now. I also think we probably should maintain these configurations in this repo, and not a separate one, since we already have some apps here, and we already have the scripts to write kde configurations. But if we are going to add more applications here. Each application should have your own maintainer, or cover only main options, or both. But we can think of it later.

**Comment by SigmaSquadron** [comment]
> Each application should have your own maintainer

I'd recommend something simple like what [treefmt-nix](https://github.com/numtide/treefmt-nix) does.
It's just a [string with your GitHub username](https://github.com/numtide/treefmt-nix/blob/5f5c2787576f3e39bbc2ebdbf8521b3177c5c19c/programs/typstyle.nix#L7).
```nix
{
  meta.maintainers = [ "SigmaSquadron" ];
}
```
Possible concerns:
- Usernames can change.
- Contributors are required to have a GitHub account.

**Comment by dweee** [comment]
> Contributors are required to have a GitHub account.

I feel it would probably be best doing something along the lines would make more sense
```nix 
{
  meta.maintainers =  ["github:dweee" "mailto:git@dave.monke.fail" "pgp:FFFFFFFF" ];
}
```
> Usernames can change.

Maybe a comment at the end of the string with a reference to the ID returned by the [GitHub API](https://api.github.com/users/dweee)?
